### ISSUE TITLE
Provide runtimes for beta NVidia drivers

### ISSUE THREAD

**Issue by tannisroot** [flathub/org.freedesktop.Platform.GL.nvidia#1]
Since NVidia offers beta drivers with things like new Vulkan extensions, which are sometimes required to run games through DXVK (used in Steam), it would be very nice if Flathub could offer runtimes for these drivers.

**Comment by TingPing** [comment]
Seems like the normal download URLs don't work for beta releases: https://download.nvidia.com/XFree86/Linux-x86_64/415.18.02/NVIDIA-Linux-x86_64-415.18.02-no-compat32.run

Perhaps you know of a usable one?

**Comment by tannisroot** [comment]
@TingPing yeah, this one: https://developer.nvidia.com/vulkan-beta-4151802-linux

**Comment by tannisroot** [comment]
@TingPing, heads up, there is a newer one available now, 415.18.04, which fixes a regression in Unity games (also present in regular 415.18).

**Comment by TingPing** [comment]
I'll change this to *patches welcomed*.

Somebody needs to update the [download script](https://github.com/flathub/org.freedesktop.Platform.GL.nvidia/blob/master/update-data.sh) to understand Vulkan beta versions and update it every time a new release comes out.

**Comment by nanonyme** [comment]
The naive approach would probably be to just add one more retry there with the developer address.

**Comment by TingPing** [comment]
Beta versions are now published.
