### ISSUE TITLE
Nvidia Driver 515.43.04 failed to build (i386)

### ISSUE THREAD

**Issue by rezzafr33** [flathub/org.freedesktop.Platform.GL.nvidia#107]
Driver 515.43.04 i386 failed to build

**Comment by d10sfan** [comment]
Not sure if it's related but I'm unable to do this as well:

flatpak install org.freedesktop.Platform.GL.nvidia-515-43-04

Looking for matches…
error: No remote refs found similar to ‘org.freedesktop.Platform.GL.nvidia-515-43-04’

It looked like the correct install name, although I also did a test where I did flatpak install org.freedesktop.Platform.GL.nvidia to list out all of the possible versions and didn't find 515.43.04.

I'm on arch linux x86-64

**Comment by rezzafr33** [comment]
@d10sfan see [this](https://flathub.org/builds/#/builders/40/builds/911)
![image](https://user-images.githubusercontent.com/275062/168081427-4eed81ae-a43d-4d80-a14f-50ab6f29ab5b.png)

**Comment by TingPing** [comment]
@barthalion Did `org.freedesktop.Sdk/i386/1.6` get deleted or something?

**Comment by Gert-dev** [comment]
In case anyone wants/needs it **right now**, I built it myself this way:

1. Clone repository.
2. Drop all versions except the beta driver version from `versions.sh` (some variables will be empty).
3. `./build.sh x86_64 build`
4. Copy `./builddir/files/manifest.json` to the repository root.
5. `flatpak-builder --user --install --force-clean build-again manifest.json`

After building and installing, it should show up with `flatpak history` as having been installed, at least for me. This works for me to get acceleration in the Firefox and Steam flatpaks until the problem is resolved.

Hope this helps someone.

**Comment by d10sfan** [comment]
@Gert-dev Does that work for 32-bit games?

**Comment by Gert-dev** [comment]
@d10sfan I haven't tested it, I only tested a 64-bit Proton game (which worked), but I'm guessing not with those steps since it doesn't install the GL32 variant. It's also listed in the `build.sh` though, and it might just be a matter of running `./build.sh i386 build` and following similar steps.

**Comment by rezzafr33** [comment]
thanks, self compiling for x86_64 works, but i386 doesn't because `org.freedesktop.Sdk/i386/1.6` can't be installed

**Comment by uncomfyhalomacro** [comment]
> thanks, self compiling for x86_64 works, but i386 doesn't because `org.freedesktop.Sdk/i386/1.6` can't be installed

since it cannot be installed, what happened to `org.freedesktop.Sdk/i386/1.6`?

**Comment by uncomfyhalomacro** [comment]
is this the same problem with https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/issues/970... smh

**Comment by TingPing** [comment]
> barthalion: I will look into restoring Platform/Sdk just to unblock this

**Comment by iotku** [comment]
515.43.04 has hit the main Arch Linux repositories so it should be a high priority to get this sorted as soon as reasonably possible.

As it stands I've had to go back to non-Flatpak applications for OBS/steam due to lack of availability as they are non-functional without an updated NVIDIA Driver.

**Comment by TheGreatestJannet** [comment]
Can the built x86_64 package be pushed to flathub to restore some functionality in the meantime?

**Comment by rezzafr33** [comment]
this repo looks interesting: https://github.com/gasinvein/org.freedesktop.Platform.GL.nvidia/tree/compat-extension-cross-rebased

**Comment by rezzafr33** [comment]
Managed to build both 64 and 32 bit drivers using @gasinvein repo, at least for beta 515.43.04.
1. Clone the fork repository, fetch all branch, checkout to `compat-extension-cross-rebased` branch.
2. Copy `data` folders from main flathub repo.
3. Drop all versions except the beta 515.43.04 driver version from versions.sh
4. Install `org.freedesktop.Sdk/x86_64/21.08` and `org.freedesktop.Sdk.Compat.i386/x86_64/21.08`
5. `make` (64 bit)
6. `make ARCH=i386` (32 bit)
7. `flatpak --user remote-add --no-gpg-verify nvidia-local repo` (add local repo, afterward you may check with `flatpak remote-ls nvidia-local`)
8. `flatpak -v install nvidia-local org.freedesktop.Platform.GL.nvidia-515-43-04`
9. `flatpak -v install nvidia-local org.freedesktop.Platform.GL32.nvidia-515-43-04`

**Comment by uncomfyhalomacro** [comment]
@rezzafr33 seems it built correctly now. :)

**Comment by d10sfan** [comment]
It's still not available it looks like.

flatpak install org.freedesktop.Platform.GL.nvidia-515-43-04
Looking for matches…
error: No remote refs found similar to ‘org.freedesktop.Platform.GL.nvidia-515-43-04’

**Comment by TheNamelessWonderer** [comment]
It is now available.
