### ISSUE TITLE
Missing 515 drivers?

### ISSUE THREAD

**Issue by VorpalBlade** [flathub/org.freedesktop.Platform.GL.nvidia#108]
After a recent update on Arch Linux, flatpak uninstalled this package without installing a matching new version. Usually this is handled automatically in the background. When I try to manually install the correct version I can't find it. My nvidia package in Arch Linux is version 515.43.04-2. I guess you are lagging behind in publishing the updated version?

**Comment by TheNamelessWonderer** [comment]
See: https://github.com/flathub/org.freedesktop.Platform.GL.nvidia/issues/107. The driver is built now so it should appear soon hopefully.

**Comment by TheNamelessWonderer** [comment]
It is now available.

**Comment by VorpalBlade** [comment]
Thanks! Yes it works.
