### ISSUE TITLE
Misising support for aarch64 production drivers

### ISSUE THREAD

**Issue by istori1** [flathub/org.freedesktop.Platform.GL.nvidia#116]
The NVIDIA production drivers are missing for aarch64. I have already tested creating a manifest for an aarch64 driver. I had to modify [update-data.sh](https://github.com/flathub/org.freedesktop.Platform.GL.nvidia/blob/master/update-data.sh) to accomplish this by hard coding it to produce the file attached. I have tested this driver to work on my aarch64 workstation. I am attaching the manifest as a txt extension, given GitHub did not allow me to upload as JSON.

NVIDIA-Linux-**aarch64**-510.73.05.**run**

[org.freedesktop.Platform.GL.nvidia-510-73-05.txt](https://github.com/flathub/org.freedesktop.Platform.GL.nvidia/files/8883710/org.freedesktop.Platform.GL.nvidia-510-73-05.txt)

**Comment by ReenigneArcher** [comment]
org.freedesktop.Platform.GL.nvidia-510-73-05.json

```json
{
    "id": "org.freedesktop.Platform.GL.nvidia-510-73-05",
    "branch": "1.4",
    "runtime": "org.freedesktop.Platform",
    "build-extension": true,
    "sdk": "org.freedesktop.Sdk",
    "runtime-version": "1.6",
    "sdk-extensions": [],
    "separate-locales": false,
    "cleanup": [ ],
    "build-options" : {
        "cflags": "-O2 -g -I/usr/lib/GL/nvidia-510-73-05/include",
        "cxxflags": "-O2 -g",
        "prefix": "/usr/lib/GL/nvidia-510-73-05",
        "env": {
            "V": "1",
            "LDFLAGS": "-L/usr/lib/GL/nvidia-510-73-05/lib"
        }
    },
    "finish-args": [
        "--extra-data=:02e6026376855c57c40f52e8b5d3c31f1ac30dd62e856ad3de7ec6fb2431a997:211202539::https://download.nvidia.com/XFree86/Linux-aarch64/510.73.05/NVIDIA-Linux-aarch64-510.73.05.run",
        "--metadata=Extra Data=NoRuntime"
    ],
    "modules": [
        {
            "cleanup": ["/include", "/share"],
            "name": "libarchive",
            "config-opts": [ "--disable-shared", "--enable-static", "--disable-xattr", "--disable-acl",
                             "--without-bz2lib", "--without-iconv", "--without-lz4", "--without-lzo2", "--without-nettle",
                             "--without-openssl", "--without-xml2", "--without-expat", "--disable-bsdcat", "--disable-bsdcpio",
                             "--disable-bsdtar"
                           ],
            "sources": [
                {
                    "type": "archive",
                    "url": "http://www.libarchive.org/downloads/libarchive-3.2.2.tar.gz",
                    "sha256": "691c194ee132d1f0f7a42541f091db811bc2e56f7107e9121be2bc8c04f1060f"
                }
            ]
        },
        {
            "name": "ldconfig",
            "buildsystem": "simple",
            "build-commands": [
                "install -Dvm755 -t ${FLATPAK_DEST}/bin/ $(which ldconfig)"
            ]
        },
        {
            "name": "nvidia",
            "make-args": [ "NVIDIA_VERSION=510-73-05", "NVIDIA_URL=https://download.nvidia.com/XFree86/Linux-aarch64/510.73.05/NVIDIA-Linux-aarch64-510.73.05.run" ],
            "no-autogen": true,
            "sources": [
                {
                    "type": "file",
                    "path": "nvidia-Makefile",
                    "dest-filename": "makefile"
                },
                {
                    "type": "file",
                    "path": "nvidia-apply-extra.c"
                }
            ]
        }
    ]
}
```

**Comment by istori1** [comment]
NVIDIA-Linux-**aarch64**-510.73.05.**run**

https://download.nvidia.com/XFree86/Linux-aarch64/510.73.05/NVIDIA-Linux-aarch64-510.73.05.run

**Comment by istori1** [comment]
> Help packaging these would be appreciated by somebody who has the hardware to test this on.

I sent an email to the address on your GitHub profile. Thank you.

**Comment by TingPing** [comment]
> I sent an email to the address on your GitHub profile. Thank you.

I appreciate the offer for access to the hardware but I also don't have the time to do the packaging and testing.

**Comment by istori1** [comment]
> > I sent an email to the address on your GitHub profile. Thank you.
> 
> I appreciate the offer for helping but I also don't have the time to do the packaging and testing.

Thanks for looking into the issue.

**Comment by istori1** [comment]
For anyone looking to use this driver on your ARM64 Machine, here are some steps :

Place the following files on your home directory:
nvidia-Makefile
nvidia-apply-extra.c
org.freedesktop.Platform.GL.nvidia-510-73-05.json

Now run the following commands
sudo flatpak install --system flathub org.flatpak.Builder org.freedesktop.Platform//1.6 org.freedesktop.Sdk//1.6
flatpak run org.flatpak.Builder --repo=nvidia --force-clean build-nvidia-driver org.freedesktop.Platform.GL.nvidia-510-73-05.json
sudo flatpak remote-add --system --no-gpg-verify testing-nvidia-driver nvidia
sudo flatpak install --system org.freedesktop.Platform.GL.nvidia-510-73-05

Now you can use Flapak apps with your GPU
