### ISSUE TITLE
Missing NVIDIA 510.73.08

### ISSUE THREAD

**Issue by cpw** [flathub/org.freedesktop.Platform.GL.nvidia#117]
Hi, Debian experimental is yet to update to the open source NVIDIA drivers (I wish I could find the discussion on this, because no doubt there is quite one going on now), and as such, they're still on the 510.73.08 version. Which is missing in flathub. Very sad.

https://tracker.debian.org/pkg/nvidia-graphics-drivers shows what versions debian supports. As you can see (on Jun 12) experimental is on 510.73.08.

I'm hopeful that this can quickly be fixed, as it is breaking the OBS package for me.

**Comment by 404NetworkError** [comment]
510.73.08 does not appear to be a public release from NVIDIA. Therefore, it's not included in this repository. (See [a list](https://www.nvidia.com/Download/Find.aspx?lang=en-us&pfid=1&psid=101&osid=12) of the latest public Linux 64-bit releases.)

You have a few options:

1. Wait for NVIDIA to publicly release version 510.73.08
2. Wait for the Debian maintainers to update their version to a public release
3. Use a public release supported by this repository

**Comment by scaledteam** [comment]
Debian testing provides "Tesla" version of their drivers. It's a usual driver but with little changes compared to original + Tesla support.
https://wiki.debian.org/NvidiaGraphicsDrivers#Tesla_Drivers

This is the driver:
https://www.nvidia.com/download/driverResults.aspx/187950/en-us/
https://docs.nvidia.com/datacenter/tesla/tesla-release-notes-510-73-08/index.html

Also the Debian package:
https://packages.debian.org/source/bookworm/nvidia-graphics-drivers-tesla-510
