### ISSUE TITLE
32-bit builds are failing again

### ISSUE THREAD

**Issue by guihkx** [flathub/org.freedesktop.Platform.GL.nvidia#136]
Same issue as https://github.com/flathub/org.freedesktop.Platform.GL.nvidia/issues/107, apparently.

Failed build job (as of commit https://github.com/flathub/org.freedesktop.Platform.GL.nvidia/commit/1fd8c1e2428add9b81ecb2052bccd2202db7686a): https://buildbot.flathub.org/#/builders/39/builds/2

Log, for future reference:

```
FB: Running: flatpak --user info org.freedesktop.Sdk/i386/1.6 --show-commit
Installing org.freedesktop.Sdk/i386/1.6 from flathub
FB: Using Flatpak version 1.14.0
FB: Running: flatpak --user install -y --noninteractive flathub org.freedesktop.Sdk/i386/1.6
Note that the directories 
'/var/lib/flatpak/exports/share'
'/srv/buildbot/.local/share/flatpak/exports/share'
are not in the search path set by the XDG_DATA_DIRS environment variable, so
applications installed by Flatpak may not appear on your desktop until the
session is restarted.
error: Nothing matches org.freedesktop.Sdk in remote flathub
Error installing deps: running `flatpak --user install -y --noninteractive flathub org.freedesktop.Sdk/i386/1.6`: Child process exited with code 1
program finished with exit code 1
```

**Comment by TingPing** [comment]
CC @barthalion again in case it was removed.

**Comment by guihkx** [comment]
Seems like it's solved now. 

[Last build job](https://buildbot.flathub.org/#/builders/12/builds/2) (commit https://github.com/flathub/org.freedesktop.Platform.GL.nvidia/commit/2bb5c3794c0ddaa17d4834de90153904f367aab2) has passed.

**Comment by barthalion** [comment]
Not sure what happened here as it was not removed again.

**Comment by guihkx** [comment]
Although the last build has passed, it displayed this warning:

```
F: Warning: Treating remote fetch error as non-fatal since runtime/org.freedesktop.Sdk/i386/1.6 is already installed: No such ref 'runtime/org.freedesktop.Sdk/i386/1.6' in remote flathub
Info: org.freedesktop.Sdk is end-of-life, with reason: The Freedesktop 1.6 SDK is no longer supported and does not receive security updates. We strongly recommend migrating to a supported runtime.
```

Which got me wondering if it's intentional that `org.freedesktop.Sdk/i386/1.6` is not publicly available for installation?

```
$ flatpak remote-info --log flathub org.freedesktop.Sdk/i386/1.6
error: Error searching remote flathub: Can't find ref org.freedesktop.Sdk/i386/1.6
```

**Comment by TingPing** [comment]
I'm not sure about public availability but I will mention this package is *very* unique in that it sets the `NoRuntime` property. The end package does not depend on any runtime and its only used for building.
