### ISSUE TITLE
Nvidia driver 525.60.13 x86_64 not found

### ISSUE THREAD

**Issue by HybridSquirrel** [flathub/org.freedesktop.Platform.GL.nvidia#144]
Hi

I'm new to flatpak/flathub and to github issues.

I can't find the nvidia driver 525.60.13 x86_64 for flatpak at flathub.
Is it because the driver is categorized as tesla driver? 
If so how do i install it? 
and/or is it possible to install the driver for flatpak manually by pull from this repo and installing it somehow?

**Comment by mazen-mardini** [comment]
It seems that it's not available in the repository:
```bash
flatpak install org.freedesktop.Platform.GL.nvidia-525-60-13
```
Only 525-60-11 is.

**Comment by TingPing** [comment]
The build failed, I've triggered a new one: https://buildbot.flathub.org/#/builders/6/builds/11118

**Comment by TingPing** [comment]
Hmm, `Installing org.freedesktop.Sdk/i386/1.6 from flathub` is failing, which has happened in the past. Will give it some time and try again.

**Comment by TingPing** [comment]
Worked this time: https://buildbot.flathub.org/#/builders/6/builds/11120

**Comment by HybridSquirrel** [comment]
My drivers are working again. Thank you guys so much, really appreciate it!
