### ISSUE TITLE
WebKitGTK not working within apps, with nvidia-340

### ISSUE THREAD

**Issue by locness3** [flathub/org.freedesktop.Platform.GL.nvidia#145]
I'm running the following :
- Ubuntu 20.04
- NVIDIA binary driver 340.108 with the matching org.freedesktop.Platform.GL.nvidia-340-108 Flatpak from Flathub (laptop with old NVIDIA GeForce 9400M GPU, no Intel graphics, nouveau is not very usable on this)
-  Linux kernel 5.4.0-135-generic (so that this driver works).

WebKitGTK is not working on this system within apps that use it. I'm trying to use GNOME apps on their latest versions such as Epiphany (Web) and Apostrophe (the HTML preview feature) through Flatpak, from Flathub. 
Nothing ever displays in the web views of these apps (while everything else works fine). When I run such an app through a terminal, I get the following errors :

```
Cannot create EGL sharing context: error binding OpenGL API (EGL_BAD_PARAMETER)

(process:70): Gdk-WARNING **: 16:28:17.903: The program '(null)' received an X Window System error.
This probably reflects a bug in the program.
The error was '179'.
  (Details: serial 483 error_code 179 request_code 154 (unknown) minor_code 21)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the GDK_SYNCHRONIZE environment
   variable to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)
```

I'm asking here because I read OpenGL, but I have no idea what this could be about.
Any clue of how I could fix this on my side, or is this an issue with the aforementioned NVIDIA Flatpak? Or maybe with the GNOME Platform Flatpak?
This is probably the only OpenGL-using thing not working on this setup.

Thank you for your time.

**Comment by mcatanzaro** [comment]
One more thing to help this bug report, please:

```
$ flatpak run --command=/bin/bash org.gnome.Epiphany
[📦 org.gnome.Epiphany ~]$ GDK_SYNCHRONIZE=1 epiphany
```

Make it crash, then on your host system, run:

```
$ flatpak-coredumpctl org.gnome.Epiphany
(gdb) bt full
```

And attach the backtrace here. I imagine this will need to be reported further upstream, but having a backtrace here certainly won't hurt.

**Comment by TingPing** [comment]
I think all WebKit can do is use GLX again.

It's likely those drivers will never support EGL properly.

**Comment by TingPing** [comment]
Actually, WebKitGTK didn't switch to EGL until 2.39...

**Comment by locness3** [comment]
> One more thing to help this bug report, please:
> 
> ```
> $ flatpak run --command=/bin/bash org.gnome.Epiphany
> [📦 org.gnome.Epiphany ~]$ GDK_SYNCHRONIZE=1 epiphany
> ```
> 
> Make it crash, then on your host system, run:
> 
> ```
> $ flatpak-coredumpctl org.gnome.Epiphany
> (gdb) bt full
> ```
> 
> And attach the backtrace here. I imagine this will need to be reported further upstream, but having a backtrace here certainly won't hurt.

I'm a bit lost as to how to do this.

First of all I didn't have `flatpak-coredumpctl` in my PATH after installing all of the `flatpak-*` packages from the ubuntu repos. I only found what seems to be it as `/usr/share/doc/flatpak/examples/flatpak-coredumpctl`. Running this first told me that `coredumpctl` wasn't found, so I installed the `systemd-coredump` package (which removed ubuntu's `apport`, could that be bad?). Then I ran `flatpak-coredumpctl` which gave the following output :

```
Executable /usr/libexec/webkit2gtk-4.1/WebKitWebProcess doesn't seem to be a flatpaked application.
Running: `"flatpak" "run" "--filesystem=home" "--filesystem=/tmp" "--command=gdb" "--devel" "org.gnome.Epiphany" "/usr/libexec/webkit2gtk-4.1/WebKitWebProcess" "/tmp/tmpi3_e_02c"`
GNU gdb (GDB) 12.1
Copyright (C) 2022 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-unknown-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /usr/libexec/webkit2gtk-4.1/WebKitWebProcess...
Reading symbols from .gnu_debugdata for /usr/libexec/webkit2gtk-4.1/WebKitWebProcess...
(No debugging symbols found in .gnu_debugdata for /usr/libexec/webkit2gtk-4.1/WebKitWebProcess)
BFD: attention: /tmp/tmpi3_e_02c a un segment qui s'étend au delà de la fin du fichier
[New LWP 11]
[New LWP 2]
[New LWP 4]
[New LWP 3]
[New LWP 5]
[New LWP 6]
[New LWP 7]
[New LWP 8]
[New LWP 10]
[New LWP 9]

warning: Error reading shared library list entry at 0xa3e52f7400000016
Failed to read a valid object file image from memory.
--Type <RET> for more, q to quit, c to continue without paging--
```

Inputting "c" or simply pressing Enter gives the following :
```
--Type <RET> for more, q to quit, c to continue without paging--c
Core was generated by `/usr/libexec/webkit2gtk-4.1/WebKitWebProcess 22 30'.
Program terminated with signal SIGTRAP, Trace/breakpoint trap.
#0  0x00007f6c041eaf27 in ?? ()
[Current thread is 1 (LWP 11)]
(gdb) bt full
#0  0x00007f6c041eaf27 in ?? ()
No symbol table info available.
Backtrace stopped: Cannot access memory at address 0x7f6b8fffddd0
(gdb) exit
```

Apologies, I'd like to help but I honestly have zero idea what I'm doing here.

**Comment by locness3** [comment]
> I think all WebKit can do is use GLX again.
> 
> It's likely those drivers will never support EGL properly.

Oh. Doesn't sound good.

**Comment by mcatanzaro** [comment]
I see you're using Ubuntu 20.04 rather than 22.04, though. I bet flatpak-coredumpctl is packaged properly in newer versions. It indeed used to be packaged as a documentation file, but that was just a mistake: the packager assumed it was intended to be an example and not something that would be required for debugging.

Removing apport is not good, no, but without coredumpctl you have little chance of successfully reporting bugs to upstream projects, so you kinda have to.

> Apologies, I'd like to help but I honestly have zero idea what I'm doing here.

Um, I forgot to ask you to install debuginfo. You need to `flatpak install org.gnome.Epiphany.Debug` and `flatpak install org.gnome.Platform.Debug`, then run `flatpak update` to ensure everything is at the latest version. Then you _should_ get a better backtrace. However, I'm a little worried because there's only a single frame of ?? in your backtrace. Could the core file have been truncated by systemd? If you run `coredumpctl list` and look at the bottom of the list, is the last core dump `present` or `truncated`?

**Comment by mcatanzaro** [comment]
> Oh. Doesn't sound good.

I didn't know that graphics cards without EGL support existed. That's mind-boggling to me. Honestly it's probably time to shred it and upgrade your hardware. But indeed, that shouldn't be a problem for WebKit until WebKitGTK 2.40 is released in March 2023. That will be the first release to require EGL instead of GLX. I think what you're dealing with here is just a bug like any other.

**Comment by locness3** [comment]
> You need to `flatpak install org.gnome.Epiphany.Debug` and `flatpak install org.gnome.Platform.Debug`, then run `flatpak update` to ensure everything is at the latest version.

`org.gnome.Platform.Debug` does not seem to exist at least in Flathub, so I still have the same result.

> Could the core file have been truncated by systemd? If you run coredumpctl list and look at the bottom of the list, is the last core dump present or truncated?

All the visible items are "truncated".

Though I'm not sure I understood this :

> Make it crash

What exactly should I do? I only provoked the error (happens when just starting Epiphany anyways) and hit Ctrl+C, is there a way I should do it that I don't know of?

**Comment by mcatanzaro** [comment]
> `org.gnome.Platform.Debug` does not seem to exist at least in Flathub, so I still have the same result.

I wrote the wrong thing. I meant `org.gnome.Sdk.Debug`. I even thought to myself "make sure not to type `org.gnome.Platform.Debug` about one minute before writing it out incorrectly.

That will give you debug symbols.

> All the visible items are "truncated".

OK, that's why the backtrace is no good. Try creating an /etc/systemd/coredump.conf.d with the following contents:

```
[Coredump]
ProcessSizeMax=20G
ExternalSizeMax=20G
```

That should fix the truncation problem.

**Comment by mcatanzaro** [comment]
> What exactly should I do? I only provoked the error (happens when just starting Epiphany anyways) and hit Ctrl+C, is there a way I should do it that I don't know of?

If starting Epiphany is enough to make it crash, then that's all you need to do. We know the web process is crashing due to the X error. So now just need to get a backtrace for it. Don't forget the `GDK_SYNCHRONIZE=1` environment variable!

**Comment by mcatanzaro** [comment]
Um, you'll need to install both `org.gnome.Sdk` and `org.gnome.Sdk.Debug`.

(`org.gnome.Sdk` is the same as `org.gnome.Platform` that is usually used, except it comes with some extra tools like gdb and such, and has a debuginfo extension so the backtrace can be generated.)

**Comment by locness3** [comment]
Right, I think I finally have it :
[Epiphany WebKitGTK crash EGL error backtrace.txt](https://github.com/flathub/org.freedesktop.Platform.GL.nvidia/files/10289692/Epiphany.WebKitGTK.crash.EGL.error.backtrace.txt)

**Comment by mcatanzaro** [comment]
Excellent backtrace! Now you've got a good bug report. We know it's using GLX and failing to create a GL context, and can see exactly where it's triggering an X error, so any graphics developers who look at this bug will have something to start with.

**Comment by locness3** [comment]
> I didn't know that graphics cards without EGL support existed.

FWIW, it seems to me that in my case it does support EGL, but only for OpenGL ES, as  `es2gears` is rendering fine (using OpenGL ES via EGL), and `eglinfo` gives me the following (full result : [eglinfo.txt](https://github.com/flathub/org.freedesktop.Platform.GL.nvidia/files/10344613/eglinfo.txt))
```
...
X11 platform:
EGL API version: 1.4
EGL vendor string: NVIDIA
EGL version string: 1.4
EGL client APIs: OpenGL_ES
...
```
This support seems to have been added in the Nvidia binary driver [version 331.13 beta](http://www.nvidia.com/object/linux-display-amd64-331.13-driver.html) (found that in [the EGL article's references on Wikipedia](http://www.nvidia.com/object/linux-display-amd64-331.13-driver.html)) :
> Added support for the EGL API on 32-bit platforms. Currently, the supported client APIs are OpenGL ES 1.1, 2.0 and 3.0, and the only supported window system backend is X11.

**Comment by mcatanzaro** [comment]
Honestly it sounds like WebKit is just not going to work on 32-bit NVIDIA graphics. I'm surprised we still publish 32-bit runtimes at all.

**Comment by TingPing** [comment]
> Honestly it sounds like WebKit is just not going to work on 32-bit NVIDIA graphics. I'm surprised we still publish 32-bit runtimes at all.

Only 32bit compat libraries are shipped. There isn't a 32bit runtime any more.

**Comment by suwermave** [comment]
I have an issue with GTX 1080 (Pascal)
To display pages in Epiphany and Tangram, add this variable
WEBKIT_DISABLE_DMABUF_RENDERER=1
To display videos, add variable to disable hardware acceleration (should show you in Epiphany NEVER instead of ALWAYS)

**Comment by locness3** [comment]
I don't think this is worth keeping open as it is evident that this nvidia driver version doesn't support OpenGL via EGL which is required for WebKitGTK.
