### ISSUE TITLE
Couldn't install the 525.85.05 driver, flatpak claims it is not in repository

### ISSUE THREAD

**Issue by develop7** [flathub/org.freedesktop.Platform.GL.nvidia#151]
Repro: 

Run following command:
```
flatpak install org.freedesktop.Platform.GL.nvidia-525-85-05 org.freedesktop.Platform.GL32.nvidia-525-85-05
```

Expected: runtimes are installed

Instead: Flatpak responds with following error
```
error: No remote refs found for ‘org.freedesktop.Platform.GL.nvidia’
```

Flatpak 1.14.1 on openSUSE Tumbleweed 20230118

**Comment by TingPing** [comment]
The syntax is `flatpak install <repo> [<packages...]`

You are missing `flathub`.

**Comment by TingPing** [comment]
I'd expect them to be published. *shrug*. Here is a rebuild: https://buildbot.flathub.org/#/builders/6/builds/18424

**Comment by DarkWav** [comment]
The build seems to be finished and published now, yet
`flatpak remote-info flathub org.freedesktop.Platform.GL32.nvidia-525-85-05/x86_64`
still returns:
`error: Error searching remote flathub: Can't find ref org.freedesktop.Platform.GL.nvidia-525-85-05/x86_64`
Maybe it's a problem with flathub itself?

**Comment by totof3110** [comment]
I have the same issue too. Can't install org.freedesktop.Platform.GL.nvidia-525-85-05 because can't find ref. :(

**Comment by Bitwolfies** [comment]
Yep, cannot install it for the life of me, its just not there.
![Screenshot_20230120_213421](https://user-images.githubusercontent.com/65789901/213845244-41d87a89-7238-4c35-ab9a-870a6dd70a54.png)

**Comment by develop7** [comment]
> The syntax is `flatpak install <repo> [<packages>...]`
> 
> You are missing `flathub`.

Well then documentation should be fixed, because this way flatpak just says "found matching refs in repo flathub, use it? ([y]/n)". But okay, I should've been more specific.

> (Manually installing the nvidia package is always wrong though, just `flatpak update` in the future)

I already have updated NVIDIA drivers ready to install by system's package manager. If I'll install it, then reboot, I'll have flatpaked software that uses opengl crash until `flatpak update` is done. By installing latest Nvidia package manually upfront I'll avoid unnecessary program restarts and fumbling with `flatpak update` instead of working. Bottom line is this way I am interrupting my work on my terms, you know?

Now is different matter, because updated NVIDIA driver without matching flatpak runtime would probably result in crashing software during opengl initialization, rendering it unusable.

**Comment by develop7** [comment]
@TingPing now that we have multiple confirmations, is it okay to reopen the issue?

**Comment by develop7** [comment]
Nevermind, the runtime is in there. Thanks!
