### ISSUE TITLE
nvidia-530-30-02 Error deploying: While trying to apply extra data

### ISSUE THREAD

**Issue by Tsubajashi** [flathub/org.freedesktop.Platform.GL.nvidia#160]
when trying to update flatpak after installing the newest nvidia 530 branch, this following error appears:

```
flatpak update
Looking for updates…


        ID                                                       Branch             Op            Remote             Download
 1. [✗] org.freedesktop.Platform.GL.nvidia-530-30-02             1.4                i             flathub            344,1 MB / 345,0 MB

Warning: Error deploying: While trying to apply extra data: apply_extra script failed, exit status 256
Installation complete.
```

This happens on a fresh Arch install.

If you need any more information about the issue, please let me know and ill add it to the thread here.

Thanks in advance!

**Comment by struq** [comment]
Log message:
`flatpak-system-helper[10849]: archive_read_open_fd: Unrecognized archive format`

From driver changelog:
> Changed the compression format of the .run installer package from xz to zstd. This results in a smaller compressed package, and faster decompression performance. A fallback zstd decompressor is embedded into the installer package for systems which do not already have a zstd decompression program installed. 

Looks like the apply-extra program has not supported zstd yet.
https://github.com/flathub/org.freedesktop.Platform.GL.nvidia/blob/1c612da92545d84d6ee0c700f0a695795ae2eafa/nvidia-apply-extra.c#L200-L205

**Comment by RomanAverin** [comment]
Same issue

**Comment by IceCr34m** [comment]
same here 

```shell
 1.	  	org.freedesktop.Platform.GL.nvidia-530-30-02	1.4	i	flathub	< 345.0 MB

Proceed with these changes to the system installation? [Y/n]: y
Installing…                                                                                                                              F: Calling system helper: GetRevokefsFd
F: Calling system helper: GetRevokefsFd
F: flatpak_dir_pull: Using commit 1a301f88dc034c38d384b0c43bddb3ab09d1eacb89626f5a523a13d4b5488951 for pull of ref runtime/org.freedesktop.Platform.GL.nvidia-530-30-02/x86_64/1.4 from remote flathub

Installing…                        0%  0 bytes/s
Installing… █                      5%F: Loading https://us.download.nvidia.com/XFree86/Linux-x86_64/530.30.02/NVIDIA-Linux-x86_64-530.30.02.run using libsoup

Installing… ██▌                   13%  20.9 MB/s
Installing… █████                 25%  31.8 MB/s
Installing… ████████▌             43%  43.9 MB/s
Installing… ███████████▌          58%  46.9 MB/s  00:02
Installing… ██████████████▍       72%  48.1 MB/s  00:01
Installing… ████████████████▊     84%  47.7 MB/s  00:01
Installing… ██████████████████▊   94%  46.0 MB/s  00:00
Installing… ████████████████████ 100%  49.2 MB/s  00:00F: Received 344142236 bytes
F: Calling system helper: Deploy
Warning: Error deploying: While trying to apply extra data: apply_extra script failed, exit status 256 
```

**Comment by Tsubajashi** [comment]
i think i do definitely need a guide on how to build it from here, the command "flatpak update" still refuses to work with the same error as in the beginning of the thread... :(

**Comment by guihkx** [comment]
Tha's because the driver hasn't been published to Flathub yet.

It *usually* takes 3 hours after all builds succeed.

**Comment by Tsubajashi** [comment]
ahhh i see, sorry!

**Comment by guihkx** [comment]
They're published now :)

Feel free to test it, and re-open this if it doesn't work.
