### ISSUE TITLE
Very slow speed when upgrading

### ISSUE THREAD

**Issue by Corrupter-rot** [flathub/org.freedesktop.Platform.GL.nvidia#172]
When upgrading flatpak packages only `org.freedesktop.Platform.GL.nvidia` packages have a very slow download speeds, followed by connecting dying after sometime.

![image](https://user-images.githubusercontent.com/75395993/231781238-99e94489-6f93-473c-b100-94f1cae4fb28.png)

I have search the internet for solutions but didn't found any. Therefore opening an issue here.

**Comment by TingPing** [comment]
It is downloaded from nvidia's server.

This will eventually be fixed by #167

Closing as nothing actionable can be done atm.
