### ISSUE TITLE
NVIDIA 525.116.03 not availabe on Flathub

### ISSUE THREAD

**Issue by DarkWav** [flathub/org.freedesktop.Platform.GL.nvidia#174]
Any idea why 525.116.03 is not available on flathub?
Is it because the [i386 build failed](https://buildbot.flathub.org/#/builders/38/builds/11)?
Thanks.

**Comment by 404NetworkError** [comment]
Rebuilding

**Comment by 404NetworkError** [comment]
[Rebuilding](https://buildbot.flathub.org/#/builders/6/builds/37621)

**Comment by DarkWav** [comment]
So, it looks like the rebuild did finish successfully and has been published, but the update has not appeared in flathub repos (dl.flathub.org) so far.
Is it normal for nvidia drivers to take 5+ hours to upload to the repos?

**Comment by TingPing** [comment]
I believe actual deployment takes some hours. 5 might be on the high end. I'd give it a short while longer.

**Comment by DarkWav** [comment]
> I believe actual deployment takes some hours. 5 might be on the high end. I'd give it a short while longer.

Thanks, I will check tomorrow and report back if it is not published by then.

**Comment by DarkWav** [comment]
So it has been 10 hours, is it possible that the deployment may have failed?

**Comment by TingPing** [comment]
cc @barthalion

**Comment by barthalion** [comment]
You will need to start a new build.

**Comment by 404NetworkError** [comment]
[Trying again](https://buildbot.flathub.org/#/builders/6/builds/37862)

**Comment by DarkWav** [comment]
The update has now arrived at flathub repos and works correctly.
Thanks everyone!
