### ISSUE TITLE
Failed build

### ISSUE THREAD

**Issue by MisterSheeple** [flathub/org.freedesktop.Platform.GL.nvidia#189]

**Comment by 404NetworkError** [comment]
Ping @barthalion. It appears custom `build.sh` are broken (see one of the [latest build attempts](https://buildbot.flathub.org/#/builders/6/builds/50634)).

**Comment by Sinaaaa** [comment]
The lack of ..525.125.06 in the flathub repo really breaking my system right now. That failed to build as well?

**Comment by MisterSheeple** [comment]
> The lack of ..525.125.06 in the flathub repo really breaking my system right now. That failed to build as well?
> 
> edit: Stupid question, well 'fighting!'.

Yep, it's currently wreaking havoc on my system as well. Worst of all, this is the driver I was given upon installation of my OS, so I didn't know it was suddenly not going to work with most Flatpaks until it was too late.

**Comment by Sinaaaa** [comment]
> 

It's almost like Canonical jumped on the opportunity to push 525.125.06 from jammy.updates at the precise time, when org.freedesktop.Platform.GL.nvidia  has a problem.  I'm wrong, probably.

**Comment by barthalion** [comment]
Started a new build at https://buildbot.flathub.org/#/builders/6/builds/51098.

**Comment by MisterSheeple** [comment]
Looks like it worked, closing.
