### ISSUE TITLE
Need 545.23.08

### ISSUE THREAD

**Issue by dnadle** [flathub/org.freedesktop.Platform.GL.nvidia#213]
Latest version on cuda-rhel9 repo is 545.23.08.

**Comment by peetcamron** [comment]
And the driver is missing from the NVIDIA unix driver archive needed by this script (https://www.nvidia.com/en-us/drivers/unix/)

https://forums.developer.nvidia.com/t/545-23-08-is-not-listed-in-the-nvidia-driver-downloads-page/273181

**Comment by rambo919** [comment]
I just noticed that because of this problem most flatpaks refuse to launch for me now

**Comment by rambo919** [comment]
I found a potential reason for all the woes, there is a driver version mismatch

https://forums.developer.nvidia.com/t/545-23-08-is-not-listed-in-the-nvidia-driver-downloads-page/273181/5

**Comment by WizardOfWor1969** [comment]
Got this too , no OpenGL apps seem to be running. I tested GZDoom and Blender even Tellico.

**Comment by rambo919** [comment]
No changes my side yet.... is there something specific I need to download or should I just wait?

**Comment by rambo919** [comment]
Now it causes this [https://github.com/flathub/org.freedesktop.Platform.GL.nvidia/issues/217](url)

**Comment by IanTrudel** [comment]
I'm getting `error: Failed to install org.freedesktop.Platform.GL.nvidia-545-23-08: Error pulling from repo: ..."` after or nearby completion of downloading the file.

**Comment by WizardOfWor1969** [comment]
I get Warning: Error pulling from repo: Error reading from file: Bad address
