### ISSUE TITLE
can't update nvidia - TLS error

### ISSUE THREAD

**Issue by Pshemas** [flathub/org.freedesktop.Platform.GL.nvidia#23]
As I've got an update for the system Nvidia driver I immediately went for updating Flatpak as well (via flatpak update). All the other runtimes updates normally but Nvidia one (430.14 - but tried manually invoking others just to see what happens and I'm getting the same) fails. I get:

```
Installing: org.freedesktop.Platform.GL.nvidia-430-14/x86_64/1.4 from flathub
[#=                  ] Downloading files: 1/1 569 bytes         
error: While downloading https://us.download.nvidia.com/XFree86/Linux-x86_64/430.14/NVIDIA-Linux-x86_64-430.14-no-compat32.run: Error writing data to TLS socket: The specified session has been invalidated for some reason.
```
Any ideas what's wrong and how to fix it? It basically made all my flatpaked apps borked atm.

**Comment by Pshemas** [comment]
is there a way to pre-download files from Nvidia site as it is the part that's failing? I can download those via web browser without issue, those only fail during flatpak update.

**Comment by TingPing** [comment]
I don't believe so. There also isn't anything this package can do about it.

**Comment by Pshemas** [comment]
ok, so is there a way to build such runtime locally? This is a real bummer on my end - tried most of the solutions suggested in other topics (syncing time, disabling ipv6 etc) plus various other ones (vpn, other machine connected to other network etc) and still no luck. It literally mean goodbye to Flatpak on my end - and heck, I'd prefer to keep using it as I come to love it.

**Comment by VortexAcherontic** [comment]
I've got the same issue and first noticed it several days ago. it happens with any NVidia package.
Every other application installed through flatpak installs and updates just fine.

**Comment by TingPing** [comment]
I don't know of workarounds offhand but this is probably better discussed with the wider flatpak community (maybe on the irc channel).

**Comment by VortexAcherontic** [comment]
Today I was able to update the nv packages through flatpak. Seems to be fixed I guess.

**Comment by 404NetworkError** [comment]
@Pshemas Are you still having issues? If not, I will close this issue.

**Comment by 404NetworkError** [comment]
Feel free to reopen if you are still having issues.
