### ISSUE TITLE
Document the way to add/build/install the driver

### ISSUE THREAD

**Issue by rkfg** [flathub/org.freedesktop.Platform.GL.nvidia#282]
Flatpak driver update lags quite a bit. As I'm writing this, the newest driver 560.35.03 is added to this repo but is still absent at flathub. Because of that any non-basic GUI software fails to launch completely (Krita, Blender, Shotcut etc.). There should be a simple script that does everything needed to install the driver update locally, without waiting for flathub. I suppose the procedure is trivial, the binary driver is downloaded, unpacked, the required libraries are installed and everything just works. This issue clearly happens *way too often* to ignore and tell people to wait.

I found [these instructions](https://github.com/flathub/org.freedesktop.Platform.GL.nvidia/issues/107#issuecomment-1126341081) which for whatever reason don't install something correctly. First, the `flathub` repo should be added manually for `build.sh` to work at all. I have `flathub` added for `system` but not `user`, everything worked just fine. I added this repo for user, now when I install anything flatpak asks me which repo of the two to use. I assume this can be mitigated somehow.

I did what the instructions say, the binary driver was downloaded but something went wrong (even though there were no errors) and nothing actually changed. `flatpak history` shows `deploy install org.freedesktop.Platform.GL.nvidia-560-35-03`, I'm not sure what else I can check.

Ideally, I see this working like this:
- launch `./install.sh` (or similar)
- it runs `nvidia-smi` to get the current driver version
- does everything needed to download and repack the driver
- installs it locally just like any other flatpak
- all software starts working as before

**Comment by rkfg** [comment]
I'm fully okay with the 32-bit part missing, I have no such software anyway. I tried your instructions in the pull request, something is missing. I did `flatpak build-bundle repo nvidia-driver.flatpak org.freedesktop.Platform.GL.nvidia-560-35-03 1.4 --runtime`, the resulting file is quite small, only 547 Kb. I then ran `flatpak install --bundle nvidia-driver.flatpak`, it asked me for my user password (this doesn't happen when I normally install flatpaks), then I got this error:
```
Error: Extra data missing in detached metadata
error: Failed to install bundle org.freedesktop.Platform.GL.nvidia-560-35-03: Extra data missing in detached metadata
```

**Comment by guihkx** [comment]
The instructions will only work reliably if you check out my branch first.

Your error is caused by https://github.com/flatpak/flatpak/issues/1334, and has no solution yet.

**Comment by failboat78** [comment]
It's true most people don't have linux 32bit software anymore. But many people run steam/wine to run 32bit windows software - which needs 32bit linux libraries.

**Comment by rkfg** [comment]
Thank you, now it works. I installed it with `flatpak --user remote-add --no-gpg-verify nvidia-local repo` and then `flatpak install org.freedesktop.Platform.GL.nvidia-560-35-03`, now my other programs work. I use flatpak mainly for the programs that are rarely updated in Debian and they all rely on OpenGL availability, so without these driver updates it all becomes unusable.

>I understand, but a lot of people need that because of legacy software and old games.

Absolutely, I can only talk about myself. But I think most people don't need that much so the installer script could help 80% of all users and nothing would change for the remaining 20% (they still need to wait for the official update). I don't know the flatpak internals, but ideally it would be great to automate this build process if the user has the required software (compiler etc.)

>But many people run steam/wine to run 32bit windows software - which needs 32bit linux libraries.

Yeah, Steam is still 32 bit and there is an unofficial flatpak of it. The games are mostly 64 bit now but it doesn't matter because Steam itself is unlikely to run without this 32 bit driver runtime. Hopefully it gets sorted soon, flatpak is great but now and then it suddenly breaks like this and it's not much fun fixing this stuff with long commands (even for a developer like myself).
