### ISSUE TITLE
i cant download 560.35.03

### ISSUE THREAD

**Issue by SteavenGamerYT** [flathub/org.freedesktop.Platform.GL.nvidia#283]
i cant download  560.35.03, when its going to be released? please i need it please just put it

**Comment by Hyphaed** [comment]
it is working, I've just compiled it

you just need to follow isntructions

**Comment by Chromiell** [comment]
> it is working, I've just compiled it
> 
> you just need to follow isntructions

Which instructions? I'm on the same boat, I updated my system to 560.35.03 and normally I just need to run `flatpak update` to refresh the Flatpaks libraries, including the Nvidia driver, but now it doesn't pull the 560.35.03 version. Has something changed with this driver release that now it requires manual intervention?

**Comment by Hyphaed** [comment]
well 560.35.03 is not available yet on flatpak repositories

you can always git clone this github repository

then you open the file versions-sh and keep it like that >>

`NEW_FEATURE_VERSIONS="560.35.03"

DRIVER_VERSIONS="$NEW_FEATURE_VERSIONS"
`

after that run

./update-data.sh

then run

make

then got to terminal and type

flatpak install nvidia-560

will appear probably 3 options

`Remotes found with refs similar to ‘nvidia-560’:

   1) ‘flathub’ (system)
   2) ‘flathub’ (user)
   3) ‘local-repo’ (user)
`

choose the option local-repo

`Found ref ‘runtime/org.freedesktop.Platform.GL.nvidia-560-35-03/x86_64/1.4’ in remote ‘local-repo’ (user).
Use this ref? [Y/n]: 
`

Install

only that I need also the org.freedesktop.Platform.GL32.nvidia-560-35-03 package

if anyone finds the solution for that, please tell

thanks

**Comment by rkfg** [comment]
For the local repo to appear you need to add it manually after `make`: `flatpak --user remote-add --no-gpg-verify local-repo repo`

**Comment by Hyphaed** [comment]
@rkfg 
any solution on how to get the
org.freedesktop.Platform.GL32.nvidia-560-35-03 compiled?

**Comment by rkfg** [comment]
@Hyphaed see #282, you need to use the not yet accepted PR #234, it allows to build both versions.

**Comment by Hyphaed** [comment]
many thanks @rkfg 

yet I get this error: 

`(base) ferran@z590i:~/Documents/PersonalPackages/org.freedesktop.Platform.GL.nvidia$ flatpak build-bundle repo/ nvidia-driver-560.35.03-32bit.flatpak org.freedesktop.Platform.GL32.nvidia-560.35.03 1.4 --runtime
error: 'org.freedesktop.Platform.GL32.nvidia-560.35.03' is not a valid name: Only last name segment can contain -
`

**Comment by rkfg** [comment]
Should be `org.freedesktop.Platform.GL32.nvidia-560-35-03`

**Comment by Hyphaed** [comment]
@rkfg 

```
(base) ferran@z590i:~/Documents/PersonalPackages/org.freedesktop.Platform.GL.nvidia$ flatpak build-bundle repo/ nvidia-driver-560.35.03-32bit.flatpak org.freedesktop.Platform.GL32.nvidia-560-35-03
error: Refspec 'app/org.freedesktop.Platform.GL32.nvidia-560-35-03/x86_64/master' not found
```

**Comment by rkfg** [comment]
Not sure what that means but I installed it via adding a local repo, not bundle. It's simpler imo.

**Comment by Hyphaed** [comment]
the thing is, I do not have gl32 on local-repo >>

`   3) ‘local-repo’ (user)

Which do you want to use (0 to abort)? [0-3]: 3
Found ref ‘runtime/org.freedesktop.Platform.GL.nvidia-560-35-03/x86_64/1.4’ in remote ‘local-repo’ (user).
Use this ref? [Y/n]: 


        ID                                                  Branch       Op       Remote           Download
 1.     org.freedesktop.Platform.GL.nvidia-560-35-03        1.4          i        local-repo       < 323,5 MB

`

**Comment by rkfg** [comment]
Interesting, try to clean up the repo with `git clean -fxd` and run `make` again. I get this:
```
> flatpak install nvidia-560-35
Looking for matches…
Similar refs found for ‘nvidia-560-35’ in remote ‘nvidia-local’ (user):

   1) runtime/org.freedesktop.Platform.GL.nvidia-560-35-03/x86_64/1.4
   2) runtime/org.freedesktop.Platform.GL32.nvidia-560-35-03/x86_64/1.4

Which do you want to use (0 to abort)? [0-2]: 
```

**Comment by Hyphaed** [comment]
same, 32bit not here :: gonan ask in the other thread

`Remotes found with refs similar to ‘nvidia-560’:

   1) ‘flathub’ (system)
   2) ‘flathub’ (user)
   3) ‘nvidia-local’ (user)

Which do you want to use (0 to abort)? [0-3]: 3
Found ref ‘runtime/org.freedesktop.Platform.GL.nvidia-560-35-03/x86_64/1.4’ in remote ‘nvidia-local’ (user).
Use this ref? [Y/n]: 





`

**Comment by Hyphaed** [comment]
ok even when they do not appear, I've just rebooted the PC and now flatpaks are working

I feel it quite weird, since I'm not fan of "reboot and all solved" option, do not really believe it works like that

**Comment by rkfg** [comment]
Maybe you're missing the 32 bit dependencies mentioned in that PR?

**Comment by Hyphaed** [comment]
@rkfg 

do not see those dependencies you talk about....

**Comment by rkfg** [comment]
It was probably in another issue and I'm unsure it would help, but I also installed `org.freedesktop.Sdk.Compat.i386/x86_64/21.08` and `org.freedesktop.Sdk.Extension.toolchain-i386/x86_64/21.08`.

**Comment by guihkx** [comment]
The only reason 560.35.03 is not on Flathub yet is because the i386 driver [is failing to build](https://buildbot.flathub.org/#/builders/44/builds/29/steps/7/logs/stdio) because of a CMake/Ninja-related error:

<details><summary>Expand</summary>

```
========================================================================
Building module libarchive in /srv/buildbot/worker/build-i386-2/build/.flatpak-builder/build/libarchive-1
========================================================================
]2;flatpak-builder: Building libarchiveFB: Running: tar xf /srv/buildbot/worker/build-i386-2/build/.flatpak-builder/downloads/f887755c434a736a609cbd28d87ddbfbe9d6a3bb5b703c22c02f6af80a802735/libarchive-3.7.4.tar.xz --no-same-owner --strip-components=1 -J
FB: Running: flatpak build --die-with-parent --env=FLATPAK_BUILDER_BUILDDIR=/run/build/libarchive --nofilesystem=host:reset --filesystem=/srv/buildbot/worker/build-i386-2/build/.flatpak-builder/build/libarchive-1 --bind-mount=/run/build/libarchive=/srv/buildbot/worker/build-i386-2/build/.flatpak-builder/build/libarchive-1 --build-dir=/run/build/libarchive --bind-mount=/run/ccache=/srv/buildbot/worker/build-i386-2/build/.flatpak-builder/ccache --unshare=network --env=SOURCE_DATE_EPOCH=1724275480 '--env=CFLAGS=-O2 -g -I/usr/lib/GL/nvidia-560-31-02/include' '--env=CXXFLAGS=-O2 -g' --env=LDFLAGS=-L/usr/lib/GL/nvidia-560-31-02/lib --env=V=1 --env=CCACHE_DIR=/run/ccache --env=PATH=/run/ccache/bin:/app/bin:/usr/bin --env=LD_LIBRARY_PATH=/app/lib:/usr/lib/GL/nvidia-560-31-02/lib --env=PKG_CONFIG_PATH=/app/lib/pkgconfig:/app/share/pkgconfig:/usr/lib/pkgconfig:/usr/share/pkgconfig:/usr/lib/GL/nvidia-560-31-02/lib/pkgconfig --env=FLATPAK_BUILDER_N_JOBS=64 /srv/buildbot/worker/build-i386-2/build/.flatpak-builder/rofiles/rofiles-VQgSi2 cmake '-DCMAKE_INSTALL_PREFIX:PATH='\''/usr/lib/GL/nvidia-560-31-02'\''' -G Ninja . -DBUILD_SHARED_LIBS=OFF -DENABLE_OPENSSL=OFF -DENABLE_LIBB2=OFF -DENABLE_LZ4=OFF -DENABLE_BZip2=OFF -DENABLE_LIBXML2=OFF -DENABLE_EXPAT=OFF -DENABLE_CNG=OFF -DENABLE_TAR=OFF -DENABLE_CPIO=OFF -DENABLE_CAT=OFF -DENABLE_UNZIP=OFF -DENABLE_XATTR=OFF -DENABLE_ACL=OFF -DENABLE_ICONV=OFF -DENABLE_TEST=OFF
CMake Error at /usr/share/cmake-3.7/Modules/CMakeDetermineCompilerId.cmake:131 (file):
  file problem creating directory:
  /run/build/libarchive/CMakeFiles/3.7.2/CompilerIdC
Call Stack (most recent call first):
  /usr/share/cmake-3.7/Modules/CMakeDetermineCompilerId.cmake:30 (CMAKE_DETERMINE_COMPILER_ID_BUILD)
  /usr/share/cmake-3.7/Modules/CMakeDetermineCCompiler.cmake:112 (CMAKE_DETERMINE_COMPILER_ID)
  CMakeLists.txt:13 (PROJECT)
CMake Error at /usr/share/cmake-3.7/Modules/CMakeDetermineCompilerId.cmake:131 (file):
  file problem creating directory:
  /run/build/libarchive/CMakeFiles/3.7.2/CompilerIdC
Call Stack (most recent call first):
  /usr/share/cmake-3.7/Modules/CMakeDetermineCompilerId.cmake:30 (CMAKE_DETERMINE_COMPILER_ID_BUILD)
  /usr/share/cmake-3.7/Modules/CMakeDetermineCCompiler.cmake:112 (CMAKE_DETERMINE_COMPILER_ID)
  CMakeLists.txt:13 (PROJECT)
CMake Error at /usr/share/cmake-3.7/Modules/CMakeDetermineCompilerId.cmake:131 (file):
  file problem creating directory:
  /run/build/libarchive/CMakeFiles/3.7.2/CompilerIdC
Call Stack (most recent call first):
  /usr/share/cmake-3.7/Modules/CMakeDetermineCompilerId.cmake:30 (CMAKE_DETERMINE_COMPILER_ID_BUILD)
  /usr/share/cmake-3.7/Modules/CMakeDetermineCCompiler.cmake:112 (CMAKE_DETERMINE_COMPILER_ID)
  CMakeLists.txt:13 (PROJECT)
-- The C compiler identification is unknown
-- Check for working C compiler: /run/ccache/bin/cc
-- Check for working C compiler: /run/ccache/bin/cc -- broken
CMake Error at /usr/share/cmake-3.7/Modules/CMakeTestCCompiler.cmake:51 (message):
  The C compiler "/run/ccache/bin/cc" is not able to compile a simple test
  program.
  It fails with the following output:
   Change Dir: /run/build/libarchive/CMakeFiles/CMakeTmp
  
  Run Build Command:"/usr/bin/ninja" "cmTC_5fec9"
  ninja: error: rebuilding 'build.ninja': stat(build.ninja): Value too large
  for defined data type
  
  
  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:13 (PROJECT)
-- Configuring incomplete, errors occurred!
See also "/run/build/libarchive/CMakeFiles/CMakeOutput.log".
See also "/run/build/libarchive/CMakeFiles/CMakeError.log".
]2;flatpak-builder: Cleanup libarchiveError: module libarchive: Child process exited with code 1
FB: Unmounting read-only fs: fusermount -uz /srv/buildbot/worker/build-i386-2/build/.flatpak-builder/rofiles/rofiles-VQgSi2
```
</details>

I think the error is caused by https://github.com/ninja-build/ninja/issues/829 and it's been solved already, but we can't really upgrade Ninja, so we might have to revert back [this change](https://github.com/flathub/org.freedesktop.Platform.GL.nvidia/commit/b1d0cafed1172544fa7ff4049a0ff12657a3de00) and go back to Autotools.

I'll open a pull request reverting that change, and hopefully Flathub should be able to build the i386 driver.
