### ISSUE TITLE
Nvidia-560-35-03

### ISSUE THREAD

**Issue by cyrneko** [flathub/org.freedesktop.Platform.GL.nvidia#287]
Hi there! I've seen there's currently some issues with building, so I'm seeking assistance in getting my Flatpak apps to run with Nvidia GL acceleration until it's resolved.

The 560.35.03 drivers *just* arrived on Fedora a day or two ago (through RPMFusion) and due to the lack of that version on Flathub, most of my Flatpaks run *without* GL Acceleration

I build a custom Fedora Atomic Desktops image on-top of ublue's Sericea-Nvidia, so I do not have control over which version of the driver is included *unless* I pin an older image entirely. *In other words, I'd like to avoid a downgrade as that is extra hassle*

I wanna make clear that I appreciate the time that goes into maintaining and this is in no way intended to pressure any of the maintainers, I'm simply looking for help at what I believe to be the right place for this

![image](https://github.com/user-attachments/assets/ae57d0e7-18e9-4d0e-bf07-ddc9f52dcf48)

**Comment by guihkx** [comment]
The 560.35.03 driver should be published to Flathub in a couple of hours:

https://buildbot.flathub.org/#/builders/6/builds/142054

I'll leave this open until that happens.

**Comment by guihkx** [comment]
560.35.03 is now live on Flathub.

Just run `flatpak update` to get it.

**Comment by rambo919** [comment]
Well it installs but nothing will run on it.

`Because after that surprise`

**Comment by cyrneko** [comment]
> Well it installs but nothing will run on it.
> 
> ```
> time="     0.041" type="warning" -> qglx_findConfig: Failed to finding matching FBConfig for QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize -1, redBufferSize 1, greenBufferSize 1, blueBufferSize 1, alphaBufferSize -1, stencilBufferSize -1, samples -1, swapBehavior QSurfaceFormat::SingleBuffer, swapInterval 1, colorSpace QColorSpace(), profile  QSurfaceFormat::NoProfile)
> time="     0.041" type="warning" -> qglx_findConfig: Failed to finding matching FBConfig for QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize -1, redBufferSize 1, greenBufferSize 1, blueBufferSize 1, alphaBufferSize -1, stencilBufferSize -1, samples -1, swapBehavior QSurfaceFormat::SingleBuffer, swapInterval 1, colorSpace QColorSpace(), profile  QSurfaceFormat::NoProfile)
> time="     0.042" type="fatal" -> Could not initialize GLX
> ```

Same here!
Downloaded the only tool I could think of, GlxInfo, despite it being deprecated to check. Everything runs with `llvmpipe` :/

**Comment by rambo919** [comment]
Updated again now, everything works again.
