### ISSUE TITLE
Install libcuda.so

### ISSUE THREAD

**Issue by gasinvein** [flathub/org.freedesktop.Platform.GL.nvidia#31]
Some apps link with `libcuda.so` without sovesion. In case if the app is proprietary, we can't make it work in flatpak by normal means.
While it's possible to do horrible hacks via wrapper to make it work, e.g. symlink the `libcuda.so.1` from GL extension to some temporary location and add it to ld library path, it's easier to just install (or symlink) the library under `libcuda.so` name.
Also AFAIK official CUDA Toolkit comes with unversioned `libcuda.so` (or used to do so).

**Comment by TingPing** [comment]
You can duplicate this line with the unversioned soname: https://github.com/flathub/org.freedesktop.Platform.GL.nvidia/blob/master/nvidia-apply-extra.c#L401

And then test it locally and submit a PR.
