### ISSUE TITLE
Please add libnvrtc to your drivers

### ISSUE THREAD

**Issue by sblantipodi** [flathub/org.freedesktop.Platform.GL.nvidia#310]
As title.
`libnvrtc` is really important to hardware accelerate many things, like GStreamer plugins.

I workarounded it with this into my manifest, but isn't it possible to bundle with the driver?

  ```
  {
      "name": "cuda-toolkit",
      "only-arches": [
        "x86_64"
      ],
      "cleanup": [
        "/cuda"
      ],
      "buildsystem": "simple",
      "build-commands": [
        "mkdir /app/cuda",
        "sh cuda_toolkit.run --silent --toolkit --toolkitpath=/app/cuda",
        "mv /app/cuda/lib64/libcudart.* /app/lib/",
        "mv /app/cuda/lib64/libcublas* /app/lib/",
        "mv /app/cuda/lib64/libnvrtc* /app/lib/"
      ],
      "sources": [
        {
          "type": "file",
          "only-arches": [
            "x86_64"
          ],
          "url": "https://developer.download.nvidia.com/compute/cuda/12.6.3/local_installers/cuda_12.6.3_560.35.05_linux.run",
          "dest-filename": "cuda_toolkit.run",
          "md5": "29d297908c72b810c9ceaa5177142abd"
        }
      ]
    },
```

Will you ever bundle libnvrtc in your driver?

**Comment by guihkx** [comment]
I'm not sure if including libraries only present in the CUDA Toolkit would be within the scope of this package. We're not packaging CUDA, after all.

Pinging @TingPing @404NetworkError for a comment.

**Comment by guihkx** [comment]
>not including them makes nvidia drivers broken and uncomplete.

Sounds like a stretch to me.

If that was true, NVIDIA would also include these libraries with the main driver package, and not exclusively in the CUDA Toolkit.

There's also the issue of the CUDA Toolkit having a totally different versioning scheme than the main drivers. How would we know which version of the CUDA Toolkit to include with a specific driver version?

>asking "developers" to build that libnvrtc by their own is too challenging IMHO.
>GitHub Actions can't do that for example.

Then perhaps you should try a different approach. If you only need nvrtc, NVIDIA seems to provide that in a much smaller standalone package [here](https://developer.download.nvidia.com/compute/cuda/redist/cuda_nvrtc/). You can find other standalone components from CUDA [here](https://developer.download.nvidia.com/compute/cuda/redist/).

**Comment by sblantipodi** [comment]
I would say include the latest version of the CUDA toolkit?

but I understand the point, thanks for the answer.... waiting for the others, if it's not possible, please close the issue.

thanks

**Comment by 404NetworkError** [comment]
I have to agree with @guihkx and the multiple issues they brought up (not included in the main driver package, how would updating the libraries work with non-CUDA drivers, etc.).

**Comment by sblantipodi** [comment]
ok, using the standalone package as suggested by @guihkx works great and it's surely better, thanks guys, closing the issue.
