### ISSUE TITLE
Broken build of 550.142

### ISSUE THREAD

**Issue by mdouchement** [flathub/org.freedesktop.Platform.GL.nvidia#317]
Hello,

The build of the latest master branch (a58ea19) seems broken for `build-i386`
https://buildbot.flathub.org/#/builders/6/builds/169000

Hence most of my Flatpak apps are broken due to the missing Flatpak 550.142 driver.

Kind regards.

**Comment by guihkx** [comment]
I've triggered a new build here:

https://buildbot.flathub.org/#/builders/6/builds/169225

This one shouldn't fail, but I'll leave this open until the build finishes.
