### ISSUE TITLE
Add Vulkan 440.66.11

### ISSUE THREAD

**Issue by atm0915** [flathub/org.freedesktop.Platform.GL.nvidia#33]
A new vulkan driver dropped a couple of days ago and unfortunately broke flatpak, looks like it needs to be fixed here?

**Comment by 404NetworkError** [comment]
Can you add a PR with the new version?

**Comment by atm0915** [comment]
I would love to, but I'm not sure exactly what the long strings of characters are before the link to the download is in the data files.
