### ISSUE TITLE
Package not found on Flathub

### ISSUE THREAD

**Issue by ddavid** [flathub/org.freedesktop.Platform.GL.nvidia#36]
The link for the package on Flathub from the repo's descritption:
https://flathub.org/apps/details/org.freedesktop.Platform.GL.nvidia
leads me to a 404 error page:
https://flathub.org/not-found

I also can't install the package with:
```bash
flatpak --user install flathub org.freedesktop.Platform.GL.nvidia
error: Error searching remote flathub: Can't find ref org.freedesktop.Platform.GL.nvidia
```

I stumbled upon this while trying to get [GreenWithEnvy](https://flathub.org/apps/details/com.leinardi.gwe) running on Ubuntu.
Let me know if you need any details or if you can't reproduce the issue.

I'm asking here since it wasn't obvious from the 404 error message what the further steps should be: it just links to the repo overview of flathub's GitHub account.

**Comment by TingPing** [comment]
Yes because that isn't a package name.

Just run `flatpak update` it automatically installs the driver you need.

**Comment by ddavid** [comment]
Thanks for the swift response. I'd still suggest changing the link in the repo description, though. as it makes it seem that it is a package/application and currently points nowhere.

As it does not install, I guess I just have the wrong driver version, thanks for the pointer.

**Comment by TingPing** [comment]
> Thanks for the swift response. I'd still suggest changing the link in the repo description, though. as it makes it seem that it is a package/application and currently points nowhere.

Done.

> As it does not install, I guess I just have the wrong driver version, thanks for the pointer.

`flatpak --gl-drivers` will tell you what version it wants, which may not be packaged.
