### ISSUE TITLE
CUDA Developer Drivers

### ISSUE THREAD

**Issue by zeevox** [flathub/org.freedesktop.Platform.GL.nvidia#39]
CUDA provides NVIDIA drivers too, for example I am running `450.36.06`

```
Sat Jul  4 09:57:48 2020       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 450.36.06    Driver Version: 450.36.06    CUDA Version: 11.0     |
|-------------------------------+----------------------+----------------------+
```

They are not available through the usual [NVIDIA Drivers page](https://www.nvidia.com/Download/index.aspx?lang=en-us) on their website but rather the [CUDA Toolkit download page](https://developer.nvidia.com/cuda-downloads?target_os=Linux&target_arch=x86_64&target_distro=Ubuntu&target_version=1804&target_type=runfilelocal).

I do not know how they may differ from the usual NVIDIA drivers. A naïve approach to adding them to flathub might be something like this, although I have not tested whether this would work:

``` shell script
diff --git a/update-data.sh b/update-data.sh
index b2c15ea..7cd5170 100755
--- a/update-data.sh
+++ b/update-data.sh
@@ -48,6 +48,13 @@ for VER in $DRIVER_VERSIONS; do
                 echo "Unable to find URL for version $VER, arch $ARCH"
                 exit 1
             fi
+        elif [[ $CUDA_VERSIONS == *$VER* ]]; then
+            CUDA_VER=${VER%%_*}
+            URL=http://developer.download.nvidia.com/compute/cuda/${CUDA_VER}/local_installers/cuda_${VER}_linux.run
+            if ! curl -f -L -o dl $URL; then
+                echo "Unable to find URL for driver version ${VER##*_} (via CUDA ${CUDA_VER})"
+                exit 1
+            fi
         else
             URL=https://us.download.nvidia.com/XFree86/Linux-${NVIDIA_ARCH}/${VER}/NVIDIA-Linux-${NVIDIA_ARCH}-${VER}${SUFFIX}.run
             if ! curl -f -o dl $URL; then


diff --git a/versions.sh b/versions.sh
index 661de3c..9e45fa6 100755
--- a/versions.sh
+++ b/versions.sh
@@ -11,8 +11,12 @@ LEGACY_VERSIONS="340.108 340.107 340.106 340.104 340.102 340.101 304.137 304.135
 # If a version already exists on any other list, please don't include it here
 TESLA_VERSIONS="440.95.01 440.64.00 440.33.01 418.152.00 418.126.02 418.116.00 418.87.01 418.87.00 418.67 418.40.04 410.129 410.79 410.72"
 
+# See this for CUDA Toolkit versions: https://developer.nvidia.com/cuda-toolkit-archive
+# these versions of the driver are already listed above: 10.2.89_440.33.01 10.1.243_418.87.00 10.1.168_418.67
+CUDA_VERSIONS="11.0.1_450.36.06 10.1.105_418.39 10.0.130_410.48"
+

 # TODO: When do we drop these?
 # Probably never: https://ahayzen.com/direct/flathub_downloads_only_nvidia_runtimes.txt
 UNSUPPORTED_VERSIONS="390.138 390.132 390.129 390.116 390.87 390.77 390.67 390.59 390.48 390.42 390.25 390.12 387.34 387.22 387.12 384.130 384.111 384.98 384.90 384.69 384.59 384.47 381.22 381.09 378.13 375.82 375.66 375.39 375.26 370.28 367.57"
 
-DRIVER_VERSIONS="$BETA_VERSIONS $VULKAN_VERSIONS $SHORT_LIVED_VERSIONS $LONG_LIVED_VERSIONS $LEGACY_VERSIONS $TESLA_VERSIONS $UNSUPPORTED_VERSIONS"
+DRIVER_VERSIONS="$BETA_VERSIONS $VULKAN_VERSIONS $SHORT_LIVED_VERSIONS $LONG_LIVED_VERSIONS $LEGACY_VERSIONS $TESLA_VERSIONS $CUDA_VERSIONS $UNSUPPORTED_VERSIONS"
```

Either way I would be interested in hearing whether these drivers should be considered for support.

**Comment by TingPing** [comment]
The versions used are kernel module versions so the CUDA version doesn't matter.

So in order for this to work all users would have to install the entire toolkit which is probably massive and not used by many. I think this should probably become a new package?

**Comment by ZeevoX** [comment]
I believe downloading the whole toolkit would not be necessary. If the user has the official [NVIDIA developer packages repository](https://developer.nvidia.com/cuda-downloads?target_os=Linux&target_arch=x86_64&target_distro=Ubuntu&target_version=1804&target_type=debnetwork) added, then they can run `sudo apt install cuda-drivers-450` which at time of writing is a 76.8 MB download and installs just the driver (version `450.36.06`). However, I am not sure whether there is a standalone `.run` file that would install that same driver.

**Comment by tkuraku** [comment]
There is a run file for the cuda install if that helps. I also have problem running flatpak with cuda installed.

https://developer.nvidia.com/cuda-downloads?target_os=Linux&target_arch=x86_64&target_distro=CentOS&target_version=8&target_type=runfilelocal

**Comment by tkuraku** [comment]
This seems to be all resolved. There was an update for the cuda drivers and after running flatpak update the correct runtime was installed for flatpak.

**Comment by tkuraku** [comment]
Every time cuda drivers are updated from the official nvidia repositories there is about a week+ lag before the corresponding flatpak runtime is available. Not sure there is much to do about it, but it would be nice to have it ready in a more timely manner.

**Comment by guihkx** [comment]
We have been packaging CUDA drivers for a while now, so this can be closed.
