### ISSUE TITLE
Optix Support?

### ISSUE THREAD

**Issue by Docmine17** [flathub/org.freedesktop.Platform.GL.nvidia#44]
Blender now support optix for non RTX video cards, in blender 2.90 the option to activate optix is not available, and the option for denoise by optix does not appear either.
In the snap and tar.xz version these options are available, and I believe that it is not a problem in the blender package in flatpak, but driver problems.

libnvoptix1 is missing?

https://ibb.co/JpD2ht1
https://ibb.co/JrHyF9J

**Comment by TingPing** [comment]
Somebody just needs to figure out which version of the driver added it and copy over the libs like so:

https://github.com/flathub/org.freedesktop.Platform.GL.nvidia/blob/73eeddcf4285d2b2a0bea7a6be8e96340b3d9e27/nvidia-apply-extra.c#L378-L390

**Comment by Docmine17** [comment]
My Drivers

estudio@pro:~$ nvidia-
nvidia-bug-report.sh     nvidia-modprobe          nvidia-smi
nvidia-cuda-mps-control  nvidia-persistenced      
nvidia-debugdump         nvidia-settings          
estudio@pro:~$ nvidia-modprobe --version

nvidia-modprobe:  version 450.66

estudio@pro:~$ flatpak --gl-drivers 
nvidia-450-66
default
host
estudio@pro:~$

**Comment by 404NetworkError** [comment]
@Docmine17 Can you confirm that the latest update works with Blender?

**Comment by Docmine17** [comment]
it's working! Muito obrigado, acho que agora posso abandonar o snap 😆
[https://ibb.co/17YsrTc](url)
