### ISSUE TITLE
Error when trying to update nvidia-450-66 and to update to nvidia-450-80

### ISSUE THREAD

**Issue by Faidros1** [flathub/org.freedesktop.Platform.GL.nvidia#46]
Linux distribution and version:

Ubuntu 20.10
Flatpak version:

1.8.2
Description of the problem:

I get

Warning: Error deploying: While trying to apply extra data: apply_extra script failed, exit status 256

when flatpak tries to update nvidia-450-66 and to install nvidia-450-80
Steps to reproduce:

flatpak update

when nvidia-450-66 is already installed.

**Comment by 404NetworkError** [comment]
How did you install the NVIDIA driver?

Because OptiX support was added in f5aeb24, anyone using Ubuntu's default `nvidia-driver-450` would need to also install `libnvidia-gl-450` which is a recommended package.

**Comment by Faidros1** [comment]
I have the nvidia-driver-450 from Ubuntu's Groovy (20.10) repo installed, and libnvidia-gl-450 (version 450.80.02-0ubuntu1) have been pulled in for both amd64 and i386.

**Comment by 404NetworkError** [comment]
I was unable to replicate the problem with a fresh install of Ubuntu 20.10.

Another option is to remove the old runtime and install the new one. (I've had to do this in the past because `flatpak update` wasn't able to automatically recognize newer NVIDIA drivers and update the runtime accordingly.) In your situation,
```bash
flatpak remove org.freedesktop.Platform.GL.nvidia-450-66
flatpak install flathub org.freedesktop.Platform.GL.nvidia-450-80-02
```

**Comment by erlisdhima** [comment]
Had the same issue. `sudo flatpak update` worked for me. :)

**Comment by erlisdhima** [comment]
You can follow the conversation here: https://github.com/flatpak/flatpak/issues/3919
This seems related to packages that need root permission to install.

**Comment by Faidros1** [comment]
Nope, sorry. I tried it with sudo update flatpak but got the same error message:

Warning: While trying to apply extra data: apply_extra script failed, exit status 256

I might try it on a clean install in a week or two when I have the time, but so far no luck.

**Comment by 404NetworkError** [comment]
@Faidros1 Are you still having issues? If we don't hear anything soon, this issue will be closed.

**Comment by 404NetworkError** [comment]
Feel free to reopen if you are still having issues.
