### ISSUE TITLE
Proxy configuration not working for NVIDIA driver download

### ISSUE THREAD

**Issue by slwr** [flathub/org.freedesktop.Platform.GL.nvidia#5]
Proxy configuration working for flathub:
$ env | grep -i proxy
https_proxy=http://user:password@proxy-dns-name:8000/
http_proxy=http://user:password@proxy-dns-name:8000/
no_proxy=localhost,127.0.0.1,proxyconf,[…]

Tried also to override proxy configuration for flatpak runtime like following:
$ flatpak override --show org.freedesktop.Platform.GL.nvidia-340-106
[Environment]
http_proxy=http://user:password@proxy-ip-addr:8000/
https_proxy=http://user:password@proxy-ip-addr:8000/
no_proxy=localhost,127.0.0.1

Issue looks like:
$ flatpak update -v org.freedesktop.Platform.GL.nvidia-340-106
F: Opening system flatpak installation at path /var/lib/flatpak
F: Opening user flatpak installation at path /home/user/.local/share/flatpak
F: No installations directory in /etc/flatpak/installations.d. Skipping
Looking for updates...
F: Fetching summary file for remote ‘flathub’
F: Transaction: update flathub:runtime/org.freedesktop.Platform.GL.nvidia-340-106/x86_64/1.4[$old]
F: Updating remote metadata for flathub
F: marking op update:runtime/org.freedesktop.Platform.GL.nvidia-340-106/x86_64/1.4 resolved to 6000f5ace4a68bd29d1bdefea300783f73f0ef4731522998b256b768ceb909bf
Updating in system:
org.freedesktop.Platform.GL.nvidia-340-106/x86_64/1.4 flathub 6000f5ace4a6
Is this ok [y/n]: y
Updating: org.freedesktop.Platform.GL.nvidia-340-106/x86_64/1.4 from flathub
F: Loading https://download.nvidia.com/XFree86/Linux-x86_64/340.106/NVIDIA-Linux-x86_64-340.106-no-compat32.run using libsoup
[#=                  ] Downloading files: 1/1 569 bytes        
Error: Failed to update org.freedesktop.Platform.GL.nvidia-340-106/x86_64/1.4: While downloading https://download.nvidia.com/XFree86/Linux-x86_64/340.106/NVIDIA-Linux-x86_64-340.106-no-compat32.run: Server returned status 407: Proxy Authentication Required
error: There were one or more errors

No issue using wget:
$ wget https://download.nvidia.com/XFree86/Linux-x86_64/340.106/NVIDIA-Linux-x86_64-340.106-no-compat32.run

Is there a way to workaround the issue?
After some googling I expect that using libcurl instead of libsoup may solve the issue?

**Comment by TingPing** [comment]
This is an issue to report to https://github.com/flatpak/flatpak since it does the downloading.
