### ISSUE TITLE
Use cn.download.nvidia.com when possible

### ISSUE THREAD

**Issue by skyzh** [flathub/org.freedesktop.Platform.GL.nvidia#52]
As an ongoing effort to make flathub easier to use in China, we previously set up a mirror in China https://github.com/flathub/flathub/issues/813#issuecomment-753815626 . But we later find that not every software is distributed directly by flathub. It seems that NVIDIA drivers are directly downloaded from NVIDIA site, and the download speed is very slow when using default URLs provided  in `org.freedesktop.Platform.GL.nvidia`.

I have two ideas on solving this issue.

1. Check IP (or system language / locale / timezone) before downloading. If it is in China, use `cn.download.nvidia.com`.
2. Add another package like `org.freedesktop.Platform.GL.nvidia-cn` and set `FLATPAK_GL_DRIVERS=nvidia-cn`.

**Comment by gzzchh** [comment]
the best match is using ip. but how to find an reliable, safe, privacy friendly service for checking location?
timezone and locale will mismatch some users.

or just add a variable to let the script choose download url?

**Comment by gzzchh** [comment]
well, the download will be done by flatpak，not the a script. so the only way to let it use the China download server is to build another app. We can do this by editing the buld script to make it generate manifests with China mirror.

**Comment by lumingzh** [comment]
I don't think using China download server will solve the problem, I can't download the .run file from nvidia website with firefox even through VPN. I think it's nvidia server's problem.

PS: the download speed of us server is fast usually when the server working normally.

**Comment by lumingzh** [comment]
looks like I'm wrong. successfully update recently through VPN, it should be unresponse of nvidia's server before....

**Comment by guihkx** [comment]
I'm not from China, but according to [this website](https://www.gdnspc.com/dns-propagation-checker/cn.html), both `us.download.nvidia.com` and `cn.download.nvidia.com` domains resolve to the same exact IP addresses, depending on which Chinese DNS resolver you're using (apparently):

![image](https://user-images.githubusercontent.com/626206/201171399-581475ba-0602-4f27-a29d-9759c5550ba8.png)

![image](https://user-images.githubusercontent.com/626206/201171371-fcda944e-51f4-48c5-b532-e65e9da3f5d9.png)

So, in theory, there shouldn't be any difference in download speeds between the two domains.

**Comment by skyzh** [comment]
Probably they've fixed this. Close for now.
