### ISSUE TITLE
Lack of hardware acceleration in ungoogled-chromium - flatpak

### ISSUE THREAD

**Issue by Baryczka** [flathub/org.freedesktop.Platform.GL.nvidia#60]
Recently I installed the "latest" legacy nvidia drivers 390.143, which allow dkms build in kernel 5.11 and some other small fixes.
After that I discovered that ungogled-chromium (flat package) stopped using Hardware acceleration.
Could this happening because of lack of flatpak 390.143 package?

So far I've created PR #59

**Comment by 404NetworkError** [comment]
#59 has been merge and published. Please update the NVIDIA package and check if this has solved your problem.

**Comment by Baryczka** [comment]
Looks like it worked as expected! Gpu acceleration to ungoogled-chromium flatpak has come back! Thanks a lot for a very fast publishing.

**Comment by fishxz** [comment]
Sorry for the offtopic, but can you explain me how you got hardware acceleration to work? Thanks

**Comment by Baryczka** [comment]
@fishxz Hey there! In fact there was two things I did and I'm not sure which one helped:
* updated org.freedesktop.Platform.GL.nvidia to 390.143 on flatpak
* updated ungogled-chromium to 90.0.4430.85

Before that I only updated nvidia-driver-390 and after that I believe hardware acceleration stopped working.

PS: I'm not counting changing flags in chromium like disable gpu blacklist and some other gpu related stuff
