### ISSUE TITLE
Install `nvngx.dll` file for drivers >= 470

### ISSUE THREAD

**Issue by gasinvein** [flathub/org.freedesktop.Platform.GL.nvidia#64]
This PE file is needed for DLSS support in Steam Play Proton. See [this](https://gitlab.steamos.cloud/steamrt/steam-runtime-tools/-/issues/71) issue for more details.

**Comment by smcv** [comment]
The tl;dr version: whatever the library directory is where the extension's `${libdir}/libGLX_nvidia.so.0` is found (on the `LD_LIBRARY_PATH` or via `ld.so.cache` or however it happens to work), you want to also ship `${libdir}/nvidia/wine/*.dll` if they exist. I think there's only a 64-bit version, unless things have changed.

**Comment by gasinvein** [comment]
Looks like there are two files: `nvngx.dll` and `_nvngx.dll` (they're different given different sizes). I wonder if we need to ship only the former or both, and, if so, is the later subject to rename.

**Comment by smcv** [comment]
Based on my discussion with Liam, I think it'll be safest to ship the entire contents of that directory, whatever current/future driver versions happen to put there.

**Comment by gasinvein** [comment]
Yeah, but there is no special directory for `.dll`s in the driver package, they're in the same directory as `.so`s and the other files.

**Comment by 404NetworkError** [comment]
To add to the discussion, the `.dll`s do not exist in the `no-compat` versions of the installer which are being used for `x86_64`.

**Comment by gasinvein** [comment]
Well, then I guess there is no other option but to switch away from no-compat .run files? At least for versions 470 and newer.
