### ISSUE TITLE
doesn't provide application profiles in /usr/share/nvidia

### ISSUE THREAD

**Issue by smcv** [flathub/org.freedesktop.Platform.GL.nvidia#66]
Quoting Austin Shafer on https://gitlab.steamos.cloud/steamrt/steam-runtime-tools/-/issues/73:

> The NVIDIA Linux driver ships a number of application specific settings in `/usr/share/nvidia/nvidia-application-profiles-*-rc` which are loaded at runtime. [...] If possible, please expose (at the bare minimum) `/usr/share/nvidia/` to games so that the proper rules can be applied to them. If `/usr/...` is not a feasible location to expose `nvidia-application-profiles-*-rc`, there are other locations in the search path [1] that `nvidia-application-profiles-*-rc` could be mapped. It would be best to also expose all entries in the search path if that is feasible.
> [1] http://us.download.nvidia.com/XFree86/Linux-x86_64/470.42.01/README/profiles.html#ApplicationProf9ccbe

For example, in my version of the NVIDIA driver, this applies various tweaks to games like Shadow of Mordor, Civ VI and Rise of the Tomb Raider, as well as to applications like Firefox and Steam.

Note that the path `/usr/share/nvidia` is hard-coded - it is not relative to the library like #64 is.

If we assume for the moment that the NVIDIA driver cannot be changed, then I think the best way to implement this in Flatpak probably goes something like this?

* In the o.fd.P.GL.nvidia extension, install `nvidia-application-profiles-*-rc` into `extra/nvidia`, with a symlink `share -> extra`
* In the freedesktop.org runtime, configure the `org.freedesktop.Platform.GL` entry point with `merge-dirs = ...;share/nvidia`
* In the freedesktop.org runtime (at least on x86_64), create a symlink `/usr/share/nvidia -> /usr/lib/${multiarch_tuple}/GL/share/nvidia`, where `${multiarch_tuple}` is `x86_64-linux-gnu` for x86_64; that might be a dangling symlink when not using NVIDIA graphics, but that seems OK, because nothing other than the NVIDIA driver should be dereferencing it
* Optionally, in Flatpak itself, expose `/etc/nvidia` from the host system in the container by default if it exists

**Comment by gasinvein** [comment]
Something like this seems proper solution. Although I'd rather omit the `share` directory and put `nvidia` right under the extension mountpoint, for consistency with `vulkan`, `glvnd` and other stuff there that is usually in `/usr/share`.

**Comment by smcv** [comment]
My only concern with that is that the NVIDIA driver seems reasonably likely to want `nvidia` subdirectories in several places (`${libdir}/nvidia`? `${libexecdir}/nvidia`?) which could collide.

**Comment by gasinvein** [comment]
Well, the extensions' `${libdir}` is the `lib` subdirectory of the extensions' mount point, so `${libdir}/nvidia` and `${datadir}/nvidia` probably won't collide.

**Comment by gasinvein** [comment]
Or we can move all the `${datadir}` stuff to `share/` subdir, adjust future FD.o runtime 21.08 to this new layout, and leave symlinks like `vulkan -> share/vulkan` for compatibility.
But this is purely hypothetical.
