### ISSUE TITLE
Create unversioned soname links

### ISSUE THREAD

**Issue by guihkx** [flathub/org.freedesktop.Platform.GL.nvidia#68]
Hi!

I'm trying to use [this](https://gitlab.com/fzwoch/obs-nvfbc) OBS plugin (in the Flatpak version of OBS), but the plugin fails trying to `dlopen("libnvidia-fbc.so.1")`. Here's the relevant log output from OBS:

```
$ com.obsproject.Studio
[...]
error: os_dlopen(libnvidia-fbc.so.1->libnvidia-fbc.so.1): libnvidia-fbc.so.1: cannot open shared object file: No such file or directory

error: Unable to load NvFBC library
warning: Failed to initialize module 'nvfbc.so'
```

However, this OBS plugin works just fine in the non-Flatpak version of OBS. 

So I tried to search for this `libnvidia-fbc.so.1` library in the Flatpak version of the NVIDIA drivers and it actually exists there, but only a file named `libnvidia-fbc.so.470.57.02`

So, I think there should be an un-versioned symlink pointing to this and other libraries (i.e. `ln -s libnvidia-fbc.so.$VERSION libnvidia-fbc.so.1`), which is what Arch Linux does for their packaging. See:

https://github.com/archlinux/svntogit-packages/blob/55d3db4c24546d94a075d8ebbdc2c3a8df2a3441/trunk/PKGBUILD#L22-L30

Thoughts?

**Comment by TingPing** [comment]
PR welcomed.

The code is just this: https://github.com/flathub/org.freedesktop.Platform.GL.nvidia/blob/master/nvidia-apply-extra.c#L405-L408

My only concern is ensuring which versions have or don't have that file, which has to be looked into.
