### ISSUE TITLE
NVIDIA Management Library (NVML) returns always 1 GPU

### ISSUE THREAD

**Issue by leinardi** [flathub/org.freedesktop.Platform.GL.nvidia#7]
This is a quite strange and hard to reproduce bug: it seems that the [`nvmlDeviceGetCount`](https://github.com/NVIDIA/nvidia-settings/blob/de6cbb6b68532a9786c64b3266eef3b0f35ede92/src/nvml.h#L2006) returns always 1 GPU when called from an app deployed with Flatpak and it returns the correct value if called directly on the host system.

To be able to reproduce this issue you need to have more than one Nvidia GPU installed on your system.

If you have the right number of cards, an easy way to reproduce the issue is using `py3nvml`:
```bash
#!/usr/bin/env python3

from py3nvml import py3nvml

if __name__ == "__main__":
    py3nvml.nvmlInit()
    print("gpu count = {}".format(py3nvml.nvmlDeviceGetCount()))
```

This is unfortunately breaking MultiGPU support for [GWE](https://flathub.org/apps/details/com.leinardi.gwe).

**Comment by TingPing** [comment]
This was fixed in `flatpak`.
