### ISSUE TITLE
Connection slowly dying

### ISSUE THREAD

**Issue by j2l** [flathub/org.freedesktop.Platform.GL.nvidia#74]
I don't undesrtand why only this package cannot update, here's the process (it's slow enough to be able to copy):
```
flatpak update
Looking for updates…


        ID                                                  Branch        Op        Remote         Download
 1.     org.freedesktop.Platform.GL.nvidia-470-63-01        1.4           i         flathub        < 223,4 MB

Proceed with these changes to the user installation? [Y/n]: 
```
Y
```
        ID                                                  Branch        Op        Remote         Download
 1. [\] org.freedesktop.Platform.GL.nvidia-470-63-01        1.4           i         flathub        1,0 kB / 223,4 MB

Installing… █▌                     8%  197 bytes/s

```
it starts at 200b/s and goes down, and it finally ends with:
```
        ID                                                  Branch        Op        Remote         Download
 1. [✗] org.freedesktop.Platform.GL.nvidia-470-63-01        1.4           i         flathub        1,0 kB / 223,4 MB

Warning: While downloading https://us.download.nvidia.com/XFree86/Linux-x86_64/470.63.01/NVIDIA-Linux-x86_64-470.63.01-no-compat32.run: Could not connect: No route to host
Installation complete.

```

"Installation complete"? Not really :)

Current flatpak source is https://dl.flathub.org/repo
I'm using optical fiber (300MBps, solid 30MBps) in Europe. Maybe this Nvidia server route is not for Europe?

Thanks for your lights on this.

**Comment by TingPing** [comment]
Its possible Nvidia has a URL that will work better for Europeans, but otherwise we don't have any control over this.

**Comment by EriksRemess** [comment]
from what it looks - us., uk., fr.download.nvidia.com resolve to the same EdgeCast IP (at least for me in Latvia). I doubt there are any faster 1st party mirrors for Europeans and 3rd party mirrors should be used at user's own risk.

**Comment by TingPing** [comment]
I'll close this since its not actionable, #42 is the step forward.
