### ISSUE TITLE
nvidia-470.74 breaks Discord on Flathub

### ISSUE THREAD

**Issue by Elinvynia** [flathub/org.freedesktop.Platform.GL.nvidia#75]
Not sure why or how to diagnose this, for anyone that runs into this, simply remove it and install the previous one as follows:

`flatpak remove org.freedesktop.Platform.GL.nvidia-470-74`
`flatpak install org.freedesktop.Platform.GL.nvidia-470.63.01`

**Comment by TingPing** [comment]
There isn't such a thing as switching driver versions, flatpak only uses one version, the host version. You can see that by running `flatpak --gl-drivers`.

If that driver is missing `flatpak update` installs it. I suspect this was your issue.

**Comment by FakeShemp** [comment]
The solution here makes Discord not find any drivers and run in software mode.

Electron apps need to have `--disable-gpu-sandbox` to load the new drivers correctly. I don't know why.

**Comment by Elinvynia** [comment]
For anyone stumbling into this issue, this is the root cause and contains the relevant information to track progress: https://www.reddit.com/r/openSUSE/comments/ptqlfu/psa_vscode_and_some_nonpatched_electron/

Note: Fedora 35 unfortunately didn't fix these issues.

**Comment by Elinvynia** [comment]
Latest Discord flatpak update fixed this, so I'm closing this.
