### ISSUE TITLE
Add 418.30 please

### ISSUE THREAD

**Issue by alex285** [flathub/org.freedesktop.Platform.GL.nvidia#8]
thats a beta driver, but thats what Rawhide is using (RPM-Fusion), and in general people are trying NVIDIA betas, so it would be nice if we had Flatpak support, plus NVIDIA doesnt update that often

418.30: https://www.nvidia.com/download/driverResults.aspx/142166/en-us

**Comment by TingPing** [comment]
Duplicate of #1
